apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-microservice
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-microservice
  template:
    metadata:
      labels:
        app: my-microservice
    spec:
      containers:
        - name: my-microservice
          image: ghcr.io/myorg/my-microservice:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@yugabyte.yugabyte.svc.cluster.local:5433/mydb"