apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
        - name: apisix
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9080