name: Deploy Microservice to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 20.213.11.2
          username: azureuser
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          
          docker build -t chrisjrleon10/my-microservice:latest .
          docker push chrisjrleon10/my-microservice:latest

      - name: Deploy terrafrom scripts
        run: |
          cd infrastruture/terraform/
          sudo apt update && sudo apt install -y wget unzip
          wget -O terraform.zip https://releases.hashicorp.com/terraform/1.7.2/terraform_1.7.2_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform --version
          az login --tenant 5fe78ac1-1afe-4009-aa04-a71efb4a5042
          terraform init
          terraform import azurerm_resource_group.aks /subscriptions/61c877df-9dd0-41e9-95e1-db9b008c5f72/resourceGroups/myResourceGroup
          terraform plan
          terraform apply -var="resource_group_name=myResourceGroup" -var="cluster_name=myAKSCluster" -auto-approve

      - name: Deploy infra with Helm
        run: |
          cd infrastruture/helm-charts/
          helm install apisix apisix/
          helm install yugabyte yugabyte/
          helm install kafka kafka/
          helm install dapr dapr/
          helm install opa opa/
          helm install keda keda/

      - name: Deploy Microservices with Helm
        run: |
          cd services/
          helm upgrade --install user-service microservice1/
          helm upgrade --install order-service microservice2/

      - name: Deploy to AKS
        run: |
          cd infrastruture/helm-charts
          kubectl apply -f manifests/microservice-deployment.yaml
          kubectl apply -f manifests/microservice-service.yaml
          kubectl apply -f manifests/microservice-ingress.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods --all-namespaces
          kubectl get pods -n my-namespace